### ISSUE TITLE
Analysis of topologies with low sample numbers

### ISSUE THREAD

**Issue by evolgen** [simonhmartin/twisst#10]
Hi Simon,

Thanks for the awesome twist!!
Can it be applied to three different cases - 1) low coverage data 2) unphased reference genomes or 3) low sample numbers per population (n=1)?

Since you mention it is dependent on allele frequencies, I wasn't sure if it's ok to naively assume frequencies of 0, 1, 0.5 for single samples.

Thanks, 
Rohit

**Comment by simonhmartin** [comment]
Hi Rohit,
When using small numbers of samples, the genome-wide average results are still reliable, but the plots across chromosomes and weightings for individual trees are not very helpful. Because the weightings are normalised, you will get many extreme values 0 or 1 with small sample sizes just due to statistical noise.
Twisst is specifically the the pat of the pipeline that analyses trees, so the quality of the data used to make those trees (e.g. read depth) is not considered by Twisst directly. The pipeline provided in the readme that uses GATK, Beagle and Phyml will be most effective with high-depth data, but if you have large sample sizes of >100 then imputation by Beagle could help to compensate for the low coverage.
I don't know what you mean by "unphased reference genome". Most published assemblies represent a single haploid genome. If both subgenomes of a diploid individual are represented within the assembly, then the pipeline provided will not work, because your reads will be split between the two haplotypes representing each chromosome. I hope this makes sense?

**Comment by evolgen** [comment]
Hi Simon,
Thank you for the detailed info. Since variant calling with low coverage data is already problematic I guess it doesn't help unless supported by large sample sizes. 
By unphased I meant a single haploid genome without the separation of haploytpes. Reads splitting between haplotypes does make sense, glad its applicable in our case!!!
