### ISSUE TITLE
error twisst: can not run twisst.py

### ISSUE THREAD

**Issue by Andrinajoro** [simonhmartin/twisst#20]
Hi Simon,
I was following your instruction in general genomics pakage and running sliding wimdow tree inference with phyml. I manage to generate the trees.gz file as an mput for twisst.py. However when running twisst.py using the following command:
python twisst.py -t all_rename_filter2_geno0_phased_renammed_chr_phyml_ML.w50.trees.gz -w output_w50.weights.csv.gz -g ang -g Bta -g bux -g der -g eur -g imb -g ory -g scr -g spe -g str -g syl --method complete --groupsFile groups.tsv;
I got the following message:
Traceback (most recent call last):
File "twisst.py", line 576, in
topoDict = makeTopoDict(taxonNames, topos, args.outgroup if args.outgroup else None)
File "twisst.py", line 325, in makeTopoDict
output["topos"] = allTopos(taxonNames, []) if topos is None else topos
File "twisst.py", line 478, in allTopos
assert 4 <= len(branches) <= 8, "Please specify between 4 and 8 unique taxon names."
AssertionError: Please specify between 4 and 8 unique taxon names.

groups.tsv as:
ang_A ang
ang_B ang
Bta_A Bta
Bta_B Bta
bux_A bux
bux_B bux
der_A der
der_B der
eur_A eur
eur_B eur
imb_A imb
imb_B imb
ory_A ory
ory_B ory
scr_A scr
scr_B scr
spe_A spe
spe_B spe
str_A str
str_B str
syl_A syl
syl_B syl

Your advice would be much appreciated
Joro

**Comment by simonhmartin** [comment]
Hi Joro,
As the error mentions "AssertionError: Please specify between 4 and 8 unique taxon names."
Twisst currently only allows a maximum of 8 groups to be specified. The reason is that with 9 groups the number of possible taxon topologies becomes far too large. Even 6 groups gives an output with 105 weighting values. One way around this is if you have pre-defined topologies you are specifically interested in, you can specify those using the just `--inputTopos` option, and only those topology counts will be recorded.

**Comment by Andrinajoro** [comment]
Hi Simon,
Forgot to thank you for your valuable help. Manage to group my samples into
6 OTUs and get my analysis to work.
Thanks again.
Joro

**Comment by simonhmartin** [comment]
No problem. Good to hear that!
