### ISSUE TITLE
Some strange results of topo weightings

### ISSUE THREAD

**Issue by yokkkkl** [simonhmartin/twisst#39]
Hi Simon, 
Thank you for your great software and pipeline. It's really useful for my analysis. 

I guess the sum of all topo weightings in one tree equals the product of the number of samples in each taxon (or N in your paper). But some trees in my data don't equal to the N while some trees do. I followed your pipeline and there was no error or warn when the scripts ran.

Here is the subset of my input file. The topo weightings of first tree seems OK because the sum of them equals N (66 * 62 * 134 * 98 = 53736144). But the second seems not good.

Do you have any idea why it happened?

My code is: python twisst.py -t subset.phyml_bionj.w100.trees.txt -w subset.output.weights.txt -g PopI -g PopVI -g PopII -g PopV --method complete --groupsFile groups.txt

Best wishes,
Junyi

[subset.output.weights.txt](https://github.com/simonhmartin/twisst/files/10887220/subset.output.weights.txt)
[subset.phyml_bionj.w100.trees.txt](https://github.com/simonhmartin/twisst/files/10887221/subset.phyml_bionj.w100.trees.txt)
[groups.txt](https://github.com/simonhmartin/twisst/files/10887222/groups.txt)

**Comment by simonhmartin** [comment]
Hi Junyi,

The short answer:
This is not a bug, but you can avoid it if you want to by setting `--abortCutoff 1000000` or larger, but this will slow do your run.

The long answer:
This has happens because of an inbuilt safety net within the code.
When running with `--method complete`, the code is checking every one of the possible combinations of leaves (in your case this is 53736144). However, the code uses a short cut to speed things up. When a tree has many monophyletic clades representing a single taxon, each leaf in that clade tells the same story, so the clade can be collapsed into a single tip that gets a larger weighting. This is described in a supplementary figure in the original paper.

This means that there will be far fewer than 53736144 unique combinations of leaves to check. When the input groups are completely or nearly completely monophyletic, this short cut provides much bigger speed ups, compared to when they are not.

To avoid long run times under `--method complete`, I built in a safety net, in which the script switches from trying to consider all combinations, to just considering a random subsample (i.e. equivalent to `--method fixed --iterations 10000`. The switch happens when the number of combinations to consider is greater than some cutoff value (defined by `--abortCutoff`. The default is 100,000. You can increase this if you like. You could also increase the value of `--iterations` for (default is 10,000), although in testing we did not see much reason for sampling more than this. Remember that this safety net is triggered in trees where there is not much signal (not much monophyly), so it is probably not worth wasting too much of the runtime on finding highly accurate weightings for those trees.

I hope this is clear.
Simon

**Comment by yokkkkl** [comment]
Hi Simon,

Many thanks for your rapid and thoughtful reply. The information you provided can really help me move forward with the next steps. I must say I'm really grateful to you.

Best wishes,
Junyi
